import '../models/alphabet_en_model.dart';

List<AlphabetEnModel> alphabetEnList = [
  AlphabetEnModel(text: 'A', audio: 'audio/alphabet_en/kid-a.mp3'),
  AlphabetEnModel(text: 'B', audio: 'audio/alphabet_en/kid-b.mp3'),
  AlphabetEnModel(text: 'C', audio: 'audio/alphabet_en/kid-c.mp3'),
  AlphabetEnModel(text: 'D', audio: 'audio/alphabet_en/kid-d.mp3'),
  AlphabetEnModel(text: 'E', audio: 'audio/alphabet_en/kid-e.mp3'),
  AlphabetEnModel(text: 'F', audio: 'audio/alphabet_en/kid-f.mp3'),
  AlphabetEnModel(text: 'G', audio: 'audio/alphabet_en/kid-g.mp3'),
  AlphabetEnModel(text: 'H', audio: 'audio/alphabet_en/kid-h.mp3'),
  AlphabetEnModel(text: 'I', audio: 'audio/alphabet_en/kid-i.mp3'),
  AlphabetEnModel(text: 'J', audio: 'audio/alphabet_en/kid-j.mp3'),
  AlphabetEnModel(text: 'K', audio: 'audio/alphabet_en/kid-k.mp3'),
  AlphabetEnModel(text: 'L', audio: 'audio/alphabet_en/kid-l.mp3'),
  AlphabetEnModel(text: 'M', audio: 'audio/alphabet_en/kid-m.mp3'),
  AlphabetEnModel(text: 'N', audio: 'audio/alphabet_en/kid-n.mp3'),
  AlphabetEnModel(text: 'O', audio: 'audio/alphabet_en/kid-o.mp3'),
  AlphabetEnModel(text: 'P', audio: 'audio/alphabet_en/kid-p.mp3'),
  AlphabetEnModel(text: 'Q', audio: 'audio/alphabet_en/kid-q.mp3'),
  AlphabetEnModel(text: 'R', audio: 'audio/alphabet_en/kid-r.mp3'),
  AlphabetEnModel(text: 'S', audio: 'audio/alphabet_en/kid-s.mp3'),
  AlphabetEnModel(text: 'T', audio: 'audio/alphabet_en/kid-t.mp3'),
  AlphabetEnModel(text: 'U', audio: 'audio/alphabet_en/kid-u.mp3'),
  AlphabetEnModel(text: 'V', audio: 'audio/alphabet_en/kid-v.mp3'),
  AlphabetEnModel(text: 'W', audio: 'audio/alphabet_en/kid-w.mp3'),
  AlphabetEnModel(text: 'X', audio: 'audio/alphabet_en/kid-x.mp3'),
  AlphabetEnModel(text: 'Y', audio: 'audio/alphabet_en/kid-y.mp3'),
  AlphabetEnModel(text: 'Z', audio: 'audio/alphabet_en/kid-z.mp3'),
];
